# Generated by Django 3.2.4 on 2021-07-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.IntegerField(),
        ),
    ]
