# Generated by Django 3.2.4 on 2021-07-22 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('contactno', models.CharField(max_length=12)),
                ('age', models.IntegerField()),
                ('enmarbe', models.IntegerField(null=True)),
                ('enmaraf', models.IntegerField(null=True)),
                ('matmarks', models.IntegerField(null=True)),
                ('gkmarks', models.IntegerField(null=True)),
                ('examtime', models.IntegerField(verbose_name=100)),
                ('mattime', models.IntegerField(verbose_name=100)),
                ('gktime', models.IntegerField(verbose_name=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
